name: Trigger auto deployment for article-extractor-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/article-extractor-api-AutoDeployTrigger-0e4f2123-6340-4f59-9afd-1da384c9900b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARTICLEEXTRACTORAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ARTICLEEXTRACTORAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ARTICLEEXTRACTORAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build, Push, and Deploy
        run: |
          # 1. Log into the registry
          az acr login --name ca996c3a513facr
          
          # 2. Build the Docker image on GitHub's servers
          docker build -t ca996c3a513facr.azurecr.io/article-extractor-api:${{ github.sha }} .
          
          # 3. Push the built image to Azure Container Registry
          docker push ca996c3a513facr.azurecr.io/article-extractor-api:${{ github.sha }}
          
          # 4. Retrieve the registry admin password
          ACR_PASSWORD=$(az acr credential show -n ca996c3a513facr --query "passwords[0].value" -o tsv)
          
          # 5. Link the Container App to the registry
          az containerapp registry set \
            --name article-extractor-api \
            --resource-group ExtractorAPI_RG \
            --server ca996c3a513facr.azurecr.io \
            --username ca996c3a513facr \
            --password $ACR_PASSWORD
            
          # 6. Deploy the new image to the Container App
          az containerapp update \
            --name article-extractor-api \
            --resource-group ExtractorAPI_RG \
            --image ca996c3a513facr.azurecr.io/article-extractor-api:${{ github.sha }}


